add clean to base
DeebotUniverse/docs pull request #100
Opened 2022-03-03 12:33 UTC by capstan1

it's a great feature, needs to be in the docs.
Also think the switches created should be explained somewhere. Maybe a new subheader "settings"?

2022-03-03 13:30 UTC, edenhaus requested changes
thanks for your contribution.
Can you please add also the command `setAutoEmpty` in the [commands section](https://deebot.readthedocs.io/advanced/data_types/json/commands/).
this help to add support for this command in the library

2022-03-03 13:30 UTC, edenhaus commented on docs/integrations/home-assistant/examples/commands.md
> +## Empty dustbin to aute-empty station
```suggestion
## Empty dustbin to auto-empty station
```

2022-03-07 21:02 UTC, capstan1 commented
I'm sorry, I have no idea what all the REST stuff is about. So I can't really help you there. 😞

2022-03-14 17:34 UTC, edenhaus commented
@Edo78 Have you the technical skills to provide more information about the command?

2022-03-16 10:31 UTC, Edo78 commented
Sorry, I copy&pasted something from an issue of the previous repo. My skill on HA are pretty low (all my automations are in node red)

2022-03-16 10:53 UTC, edenhaus commented
Thanks @capstan1

2022-03-16 10:53 UTC, merged