Create life_span.md
DeebotUniverse/docs pull request #161
Opened 2022-07-07 16:41 UTC by Marcoske23

It is similar to json. On my device change heap to dustcaseheap

2022-07-08 07:02 UTC, mrbungle64 commented
@Marcoske23 

I will have a look at the pull requests this weekend.
I think you also have to fix some of the other pull requests, right? 😉 

cc: @edenhaus

2022-07-09 19:59 UTC, mrbungle64 requested changes
@Marcoske23 
Are you sure "dustcaseheap" is lowercase?
I only know this variant: "DustCaseHeap"

2022-07-09 20:12 UTC, Marcoske23 reviewed
fix it.

2022-07-09 21:26 UTC, mrbungle64 approved these changes

2022-07-10 07:43 UTC, merged